%YAML 1.2
---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    tag: "0.0.0"
    collection_dir: ../src
    ansible_python_interpreter: python

  tasks:
    - ansible.builtin.debug:
        var: ansible_python_interpreter

    - name: Template out the galaxy.yml file.
      ansible.builtin.template:
        src: templates/galaxy.yml.j2
        dest: "{{ collection_dir ~ '/galaxy.yml' }}"
        mode: u=rw,go=r
