name: CI-PR

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - develop
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/test-paz-*.yml'
    - 'tests/test-patk-*.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci-pr.yml'
  workflow_run:
    workflows: ["build-image-pr"]
    types:
      - completed

env:
  pr_prefix: pr${{ github.event.pull_request.number }}

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pdns: [4.2, 4.3, master]
        python: [py36, py37, py38, py39]
      fail-fast: false
    container:
      image: docker://quay.io/kpfleming/apaa-test-images:${{ env.pr_prefix }}-pdns-${{ matrix.pdns }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: start pdns_server
      run: tests/start_server.sh
    - name: run tests
      run: tox -e${{ matrix.python }}-ansible --workdir /root/tox
      env:
        pdns_version: ${{ matrix.pdns }}
