name: CI

on:
  push:
    branches:
    - develop
    - 'branch-[1-9]+.[0-9]+'
    tags:
    - 'v[1-9]+.[0-9]+.[0-9]+'
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/test-paz-playbook.yml'
    - 'tests/test-patk-playbook.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'
  pull_request:
    branches:
    - develop
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/playbook.yml'
    - 'tests/test-paz-playbook.yml'
    - 'tests/test-patk-playbook.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'
  workflow_run:
    workflows: ["build-image"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pdns: [4.2, 4.3, master]
        python: [py36, py37, py38]
      fail-fast: false
    container:
      image: docker://quay.io/kpfleming/apaa-test-images:pdns-${{ matrix.pdns }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: start pdns_server
      run: tests/start_server.sh
    - name: run tests
      run: tox -e${{ matrix.python }}-ansible --workdir /root/tox
