name: CI

on:
  push:
    branches:
    - master
    - 'branch-[1-9]+.[0-9]+'
    tags:
    - 'v[1-9]+.[0-9]+.[0-9]+'
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/test-paz-playbook.yml'
    - 'tests/test-patk-playbook.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'pdns_auth_zone.py'
    - 'pdns_auth_tsigkey.py'
    - 'api-swagger.json'
    - 'tests/playbook.yml'
    - 'tests/test-paz-playbook.yml'
    - 'tests/test-patk-playbook.yml'
    - 'tests/start_server.sh'
    - '.github/workflows/ci.yml'
  repository_dispatch:
    types: [trigger-ci]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pdns: [4.2, 4.3, 4.4, master]
    container:
      image: docker://quay.io/kpfleming/apaa-test-images:pdns-${{ matrix.pdns }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: start pdns_server
      run: tests/start_server.sh
    - name: run tests with Python 3.5
      run: tox -epy35-ansible --workdir /root/tox
    - name: run tests with Python 3.6
      run: tox -epy36-ansible --workdir /root/tox
    - name: run tests with Python 3.7
      run: tox -epy37-ansible --workdir /root/tox
    - name: run tests with Python 3.8
      run: tox -epy38-ansible --workdir /root/tox
