name: Lint checks

on:
  pull_request:
    branches:
    - main
    paths:
    - 'src/**.py'
    - 'tox.ini'
    - 'workflow-support/*.sh'
    - '.github/workflows/lint.yml'

jobs:
  image_details:
    runs-on: ubuntu-22.04
    outputs:
      image_base: ${{ steps.details.outputs.image_base }}
    steps:
    - id: details
      uses: kpfleming/composite-actions/image-details@v2
  lint:
    runs-on: ubuntu-22.04
    needs:
    - image_details
    container:
      image: ${{ needs.image_details.outputs.image_base }}:main
    steps:
    - uses: kpfleming/composite-actions/lint-tox@v2
